### PR TITLE
Added the music gui, alarm tigger, and snooze

### PR DESCRIPTION
**Pull request by PappyM**
This branch adds the music gui. The user is able to delete, play, pause, stop, and upload music files. This branch also includes the code to trigger an alarm when it is time to go off. The user can click dismiss ( new button to alarm) or can click snooze. By default snooze time is set to 5 minutes but the user can change by setting the snooze time. If snooze is clicked the alarm will sound again in the snooze time.

### CODE REVIEW

**Comment by Linh1706** [comment]
I cannot run the file MusicGui.java in netbeans on Mac.
There are some problems as the screenshot below. 
It seams like the old player GUI file (MP3PlayerGUI.java) is also not work.

screen shot 2016-11-06 at 10 44 10 pm

**Comment by Linh1706** [comment]
Still cannot run in windows.
This is my netbeans windows
error musicgui

**Comment by Linh1706** [comment]
1. The Pause button in add alarm tone do not work as expected. we can remove that button. because I think the pause button is not quite useful if we cannot select only one part of the song as the alarm tone
2. The alarm tone name should appear in the add alarm tone window (in the drop-down box).

**Comment by PappyM** [comment]
Ok I will take out the pause button. The alarm tone is blank because we haven't added the files but I will stage it for the demo to the nothingatall.mp3

**Pull request merged**
